### ISSUE TITLE
پیشنهاد

### ISSUE THREAD

**Issue by vahidalvandi** [saeed-sb/ssbhesabfa#1]
سلام . خوب است که این بسته به صورت یک ماژول پایه در
composer
باشد که سایر فریم ورک ها هم بتوانند استفاده کنند

**Comment by saeed-sb** [comment]
جناب الوندی، سلام
از پیشنهاد شما بسیار خرسندم، سعی می‌کنم در اولین فرصت پینشهاد شما رو اجرایی کنم.
